home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

mybook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django admin
    path('admin/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),

    # Local apps
    path('accounts/', include('users.urls', namespace='users')),
    path('', include('home.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.CreatePost.as_view(), name='create'),
    path('<int:pk>/', views.PostDetail.as_view(), name='detail'),
    path('list/', views.PostList.as_view(), name='list'),
    path('edit/<int:pk>/', views.UpdatePost.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpPageView.as_view(), name='signup'),
    path('<int:pk>/', views.UserProfile.as_view(), name='profile')
]

home/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.text import slugify


class Post(models.Model):
    owner = models.ForeignKey(get_user_model(), related_name='post_owner', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    context = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class PostImage(models.Model):
    image = models.ImageField(upload_to='images', blank=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='images')

users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

posts/forms.py
from extra_views import InlineFormSetFactory

from posts.models import PostImage


class PostImageInline(InlineFormSetFactory):
    model = PostImage
    fields = ['image']
    factory_kwargs = {'extra': 3}

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home/home.html'

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView, ListView

from extra_views import CreateWithInlinesView, UpdateWithInlinesView

from posts.forms import PostImageInline
from posts.models import Post


class CreatePost(LoginRequiredMixin, CreateWithInlinesView):
    model = Post
    fields = ['title', 'slug', 'context']
    inlines = [PostImageInline]
    template_name = 'posts/create_post.html'
    login_url = reverse_lazy('account_login')
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PostDetail(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'


class PostList(ListView):
    model = Post
    template_name = 'posts/post_list.html'
    paginate_by = 6
    context_object_name = 'posts'


class UpdatePost(LoginRequiredMixin, UpdateWithInlinesView):
    model = Post
    fields = ['title', 'slug', 'context']
    inlines = [PostImageInline]
    template_name = 'posts/edit_post.html'
    login_url = reverse_lazy('account_login')
    success_url = reverse_lazy('home')


class DeletePost(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/delete_post.html'
    login_url = reverse_lazy('account_login')
    success_url = reverse_lazy('home')

users/views.py
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView

from users.forms import CustomUserCreationForm


class SignUpPageView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class UserProfile(DetailView):
    model = get_user_model()
    template_name = 'users/profile.html'
    context_object_name = 'user'

home/templates/home/home.html
{% extends "_base.html" %}

{% block title %} Home {% endblock %}

{% block content %}
<h1>Welcome Home</h1>
{% endblock %}

posts/templates/posts/create_post.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block title %} Add Post {% endblock %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3 class="text-center mt-3">Create a new post</h3>
    {% if form.errors %}
    {{ form.errors }}
    {% endif %}

    {{ form|crispy }}
    
    {% for form in inlines %}
    {{ form|crispy }}
    {% endfor %}

    <button class="btn btn-success btn-lg" type="submit">Create</button>
</form>

{% endblock %}

posts/templates/posts/delete_post.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %} Delete Post {% endblock %}

{% block content %}
    <form method="post" class="pt-3 mt-3 ml-5">
        {% csrf_token %}
        <h2>Are you sure you want to delete <b>{{ object }}</b>?</h2>
        <input type="submit" value="Confirm" class="btn btn-danger btn-lg mt-2"
               style="margin-left: 20em;">
    </form>
{% endblock %}

posts/templates/posts/edit_post.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block title %} Edit Post {% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3 class="text-center mt-3">Edit post</h3>
    {% if form.errors %}
    {{ form.errors }}
    {% endif %}

    {{ form|crispy }}
    
    {% for form in inlines %}
    {{ form|crispy }}
    {% endfor %}

    <button class="btn btn-success btn-lg" type="submit">Update</button>
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "_base.html" %}

{% block title %} Post {% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h3 class="card-title">{{ post.title }}</h3>
    <h5 class="card-text">Created by {{ post.owner }} at {{ post.created }}</h5>
    {% for image in post.images.all %}
      <img src="{{ image.image.url }}" class="card-img-top responsive" alt="MyBook">
    {% endfor %}
    <p class="card-text">{{ post.context }}</p>
    <a href="{% url 'posts:update' post.id %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger">Delete</a>
  </div>
</div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "_base.html" %}
{% load static %}
{% block title %} Wall {% endblock %}

{% block content %}

<div class="row">
{% for post in posts %}
    <div class="col-sm-4">
        <div class="card text-center" style="width: 18rem;">
            <a href="{% url 'posts:detail' post.id %}">
                <img src="{% static 'images/logo.ico' %}" class="card-img-top" alt="MyBook">
            </a>
            <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">By <b>{{ post.owner }}</b></p>
            <a href="{% url 'posts:detail' post.id %}" class="btn btn-primary">See</a>
            </div>
        </div>
    </div>
{% endfor %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/_base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body>

<header>
    {% include '_nav.html' %}
</header>

<div class="container">
    <div class="row">
        <div class="col-12">
            {% if messages %}
            {% for msg in messages %}
            <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{msg.message}}
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

<main class="container">
    <div class="row">
        <div class="col-12">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</main>

</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</html>

templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container">
  <a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:list' %}">Wall<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:create' %}">Add Post<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'users:profile' user.id %}">Profile<span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:signup' %}">Signup</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Signup with Github</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</div>
</nav>

users/templates/users/profile.html
{% extends "_base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
    {{ user }}
{% endblock %}